#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetBoekenApplicatie
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Boeken")]
	public partial class BoekenLinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBoek(Boek instance);
    partial void UpdateBoek(Boek instance);
    partial void DeleteBoek(Boek instance);
    partial void InsertBoekBoekenlijst(BoekBoekenlijst instance);
    partial void UpdateBoekBoekenlijst(BoekBoekenlijst instance);
    partial void DeleteBoekBoekenlijst(BoekBoekenlijst instance);
    partial void InsertBoekenlijst(Boekenlijst instance);
    partial void UpdateBoekenlijst(Boekenlijst instance);
    partial void DeleteBoekenlijst(Boekenlijst instance);
    partial void InsertCategorie(Categorie instance);
    partial void UpdateCategorie(Categorie instance);
    partial void DeleteCategorie(Categorie instance);
    partial void InsertSchoolartikel(Schoolartikel instance);
    partial void UpdateSchoolartikel(Schoolartikel instance);
    partial void DeleteSchoolartikel(Schoolartikel instance);
    partial void InsertStatus(Status instance);
    partial void UpdateStatus(Status instance);
    partial void DeleteStatus(Status instance);
    partial void InsertUitgever(Uitgever instance);
    partial void UpdateUitgever(Uitgever instance);
    partial void DeleteUitgever(Uitgever instance);
    #endregion
		
		public BoekenLinqToSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BoekenConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BoekenLinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoekenLinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoekenLinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoekenLinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Boek> Boeks
		{
			get
			{
				return this.GetTable<Boek>();
			}
		}
		
		public System.Data.Linq.Table<BoekBoekenlijst> BoekBoekenlijsts
		{
			get
			{
				return this.GetTable<BoekBoekenlijst>();
			}
		}
		
		public System.Data.Linq.Table<Boekenlijst> Boekenlijsts
		{
			get
			{
				return this.GetTable<Boekenlijst>();
			}
		}
		
		public System.Data.Linq.Table<Categorie> Categories
		{
			get
			{
				return this.GetTable<Categorie>();
			}
		}
		
		public System.Data.Linq.Table<Schoolartikel> Schoolartikels
		{
			get
			{
				return this.GetTable<Schoolartikel>();
			}
		}
		
		public System.Data.Linq.Table<SchoolartikelBoekenlijst> SchoolartikelBoekenlijsts
		{
			get
			{
				return this.GetTable<SchoolartikelBoekenlijst>();
			}
		}
		
		public System.Data.Linq.Table<Status> Status
		{
			get
			{
				return this.GetTable<Status>();
			}
		}
		
		public System.Data.Linq.Table<Titulari> Titularis
		{
			get
			{
				return this.GetTable<Titulari>();
			}
		}
		
		public System.Data.Linq.Table<Uitgever> Uitgevers
		{
			get
			{
				return this.GetTable<Uitgever>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boek")]
	public partial class Boek : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _isbn;
		
		private string _titel;
		
		private decimal _aankoopprijs;
		
		private string _categorieID;
		
		private string _uitgeverID;
		
		private EntitySet<BoekBoekenlijst> _BoekBoekenlijsts;
		
		private EntityRef<Categorie> _Categorie;
		
		private EntityRef<Uitgever> _Uitgever;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnisbnChanging(string value);
    partial void OnisbnChanged();
    partial void OntitelChanging(string value);
    partial void OntitelChanged();
    partial void OnaankoopprijsChanging(decimal value);
    partial void OnaankoopprijsChanged();
    partial void OncategorieIDChanging(string value);
    partial void OncategorieIDChanged();
    partial void OnuitgeverIDChanging(string value);
    partial void OnuitgeverIDChanged();
    #endregion
		
		public Boek()
		{
			this._BoekBoekenlijsts = new EntitySet<BoekBoekenlijst>(new Action<BoekBoekenlijst>(this.attach_BoekBoekenlijsts), new Action<BoekBoekenlijst>(this.detach_BoekBoekenlijsts));
			this._Categorie = default(EntityRef<Categorie>);
			this._Uitgever = default(EntityRef<Uitgever>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbn", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string isbn
		{
			get
			{
				return this._isbn;
			}
			set
			{
				if ((this._isbn != value))
				{
					this.OnisbnChanging(value);
					this.SendPropertyChanging();
					this._isbn = value;
					this.SendPropertyChanged("isbn");
					this.OnisbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titel", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string titel
		{
			get
			{
				return this._titel;
			}
			set
			{
				if ((this._titel != value))
				{
					this.OntitelChanging(value);
					this.SendPropertyChanging();
					this._titel = value;
					this.SendPropertyChanged("titel");
					this.OntitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aankoopprijs", DbType="Decimal(8,3) NOT NULL")]
		public decimal aankoopprijs
		{
			get
			{
				return this._aankoopprijs;
			}
			set
			{
				if ((this._aankoopprijs != value))
				{
					this.OnaankoopprijsChanging(value);
					this.SendPropertyChanging();
					this._aankoopprijs = value;
					this.SendPropertyChanged("aankoopprijs");
					this.OnaankoopprijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categorieID", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string categorieID
		{
			get
			{
				return this._categorieID;
			}
			set
			{
				if ((this._categorieID != value))
				{
					if (this._Categorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategorieIDChanging(value);
					this.SendPropertyChanging();
					this._categorieID = value;
					this.SendPropertyChanged("categorieID");
					this.OncategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uitgeverID", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string uitgeverID
		{
			get
			{
				return this._uitgeverID;
			}
			set
			{
				if ((this._uitgeverID != value))
				{
					if (this._Uitgever.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuitgeverIDChanging(value);
					this.SendPropertyChanging();
					this._uitgeverID = value;
					this.SendPropertyChanged("uitgeverID");
					this.OnuitgeverIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boek_BoekBoekenlijst", Storage="_BoekBoekenlijsts", ThisKey="id", OtherKey="id_boek")]
		public EntitySet<BoekBoekenlijst> BoekBoekenlijsts
		{
			get
			{
				return this._BoekBoekenlijsts;
			}
			set
			{
				this._BoekBoekenlijsts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Boek", Storage="_Categorie", ThisKey="categorieID", OtherKey="categorieID", IsForeignKey=true)]
		public Categorie Categorie
		{
			get
			{
				return this._Categorie.Entity;
			}
			set
			{
				Categorie previousValue = this._Categorie.Entity;
				if (((previousValue != value) 
							|| (this._Categorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorie.Entity = null;
						previousValue.Boeks.Remove(this);
					}
					this._Categorie.Entity = value;
					if ((value != null))
					{
						value.Boeks.Add(this);
						this._categorieID = value.categorieID;
					}
					else
					{
						this._categorieID = default(string);
					}
					this.SendPropertyChanged("Categorie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uitgever_Boek", Storage="_Uitgever", ThisKey="uitgeverID", OtherKey="uitgeverID", IsForeignKey=true)]
		public Uitgever Uitgever
		{
			get
			{
				return this._Uitgever.Entity;
			}
			set
			{
				Uitgever previousValue = this._Uitgever.Entity;
				if (((previousValue != value) 
							|| (this._Uitgever.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uitgever.Entity = null;
						previousValue.Boeks.Remove(this);
					}
					this._Uitgever.Entity = value;
					if ((value != null))
					{
						value.Boeks.Add(this);
						this._uitgeverID = value.uitgeverID;
					}
					else
					{
						this._uitgeverID = default(string);
					}
					this.SendPropertyChanged("Uitgever");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Boek = this;
		}
		
		private void detach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Boek = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoekBoekenlijst")]
	public partial class BoekBoekenlijst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _klas;
		
		private int _id_boek;
		
		private System.Nullable<decimal> _huurprijs;
		
		private System.Nullable<decimal> _schoolprijs;
		
		private System.Nullable<byte> _wordtverhuurd;
		
		private string _categorieID;
		
		private EntityRef<Boek> _Boek;
		
		private EntityRef<Boekenlijst> _Boekenlijst;
		
		private EntityRef<Categorie> _Categorie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnklasChanging(string value);
    partial void OnklasChanged();
    partial void Onid_boekChanging(int value);
    partial void Onid_boekChanged();
    partial void OnhuurprijsChanging(System.Nullable<decimal> value);
    partial void OnhuurprijsChanged();
    partial void OnschoolprijsChanging(System.Nullable<decimal> value);
    partial void OnschoolprijsChanged();
    partial void OnwordtverhuurdChanging(System.Nullable<byte> value);
    partial void OnwordtverhuurdChanged();
    partial void OncategorieIDChanging(string value);
    partial void OncategorieIDChanged();
    #endregion
		
		public BoekBoekenlijst()
		{
			this._Boek = default(EntityRef<Boek>);
			this._Boekenlijst = default(EntityRef<Boekenlijst>);
			this._Categorie = default(EntityRef<Categorie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klas", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string klas
		{
			get
			{
				return this._klas;
			}
			set
			{
				if ((this._klas != value))
				{
					if (this._Boekenlijst.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnklasChanging(value);
					this.SendPropertyChanging();
					this._klas = value;
					this.SendPropertyChanged("klas");
					this.OnklasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_boek", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_boek
		{
			get
			{
				return this._id_boek;
			}
			set
			{
				if ((this._id_boek != value))
				{
					if (this._Boek.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_boekChanging(value);
					this.SendPropertyChanging();
					this._id_boek = value;
					this.SendPropertyChanged("id_boek");
					this.Onid_boekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huurprijs", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> huurprijs
		{
			get
			{
				return this._huurprijs;
			}
			set
			{
				if ((this._huurprijs != value))
				{
					this.OnhuurprijsChanging(value);
					this.SendPropertyChanging();
					this._huurprijs = value;
					this.SendPropertyChanged("huurprijs");
					this.OnhuurprijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolprijs", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> schoolprijs
		{
			get
			{
				return this._schoolprijs;
			}
			set
			{
				if ((this._schoolprijs != value))
				{
					this.OnschoolprijsChanging(value);
					this.SendPropertyChanging();
					this._schoolprijs = value;
					this.SendPropertyChanged("schoolprijs");
					this.OnschoolprijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wordtverhuurd", DbType="TinyInt")]
		public System.Nullable<byte> wordtverhuurd
		{
			get
			{
				return this._wordtverhuurd;
			}
			set
			{
				if ((this._wordtverhuurd != value))
				{
					this.OnwordtverhuurdChanging(value);
					this.SendPropertyChanging();
					this._wordtverhuurd = value;
					this.SendPropertyChanged("wordtverhuurd");
					this.OnwordtverhuurdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categorieID", DbType="Char(4)")]
		public string categorieID
		{
			get
			{
				return this._categorieID;
			}
			set
			{
				if ((this._categorieID != value))
				{
					if (this._Categorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategorieIDChanging(value);
					this.SendPropertyChanging();
					this._categorieID = value;
					this.SendPropertyChanged("categorieID");
					this.OncategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boek_BoekBoekenlijst", Storage="_Boek", ThisKey="id_boek", OtherKey="id", IsForeignKey=true)]
		public Boek Boek
		{
			get
			{
				return this._Boek.Entity;
			}
			set
			{
				Boek previousValue = this._Boek.Entity;
				if (((previousValue != value) 
							|| (this._Boek.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Boek.Entity = null;
						previousValue.BoekBoekenlijsts.Remove(this);
					}
					this._Boek.Entity = value;
					if ((value != null))
					{
						value.BoekBoekenlijsts.Add(this);
						this._id_boek = value.id;
					}
					else
					{
						this._id_boek = default(int);
					}
					this.SendPropertyChanged("Boek");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boekenlijst_BoekBoekenlijst", Storage="_Boekenlijst", ThisKey="klas", OtherKey="klas", IsForeignKey=true)]
		public Boekenlijst Boekenlijst
		{
			get
			{
				return this._Boekenlijst.Entity;
			}
			set
			{
				Boekenlijst previousValue = this._Boekenlijst.Entity;
				if (((previousValue != value) 
							|| (this._Boekenlijst.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Boekenlijst.Entity = null;
						previousValue.BoekBoekenlijsts.Remove(this);
					}
					this._Boekenlijst.Entity = value;
					if ((value != null))
					{
						value.BoekBoekenlijsts.Add(this);
						this._klas = value.klas;
					}
					else
					{
						this._klas = default(string);
					}
					this.SendPropertyChanged("Boekenlijst");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_BoekBoekenlijst", Storage="_Categorie", ThisKey="categorieID", OtherKey="categorieID", IsForeignKey=true)]
		public Categorie Categorie
		{
			get
			{
				return this._Categorie.Entity;
			}
			set
			{
				Categorie previousValue = this._Categorie.Entity;
				if (((previousValue != value) 
							|| (this._Categorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorie.Entity = null;
						previousValue.BoekBoekenlijsts.Remove(this);
					}
					this._Categorie.Entity = value;
					if ((value != null))
					{
						value.BoekBoekenlijsts.Add(this);
						this._categorieID = value.categorieID;
					}
					else
					{
						this._categorieID = default(string);
					}
					this.SendPropertyChanged("Categorie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boekenlijst")]
	public partial class Boekenlijst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _klas;
		
		private int _statusID;
		
		private string _opmerking;
		
		private System.DateTime _laatstewijziging;
		
		private System.Nullable<int> _aantalLeerlingen;
		
		private EntitySet<BoekBoekenlijst> _BoekBoekenlijsts;
		
		private EntityRef<Status> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnklasChanging(string value);
    partial void OnklasChanged();
    partial void OnstatusIDChanging(int value);
    partial void OnstatusIDChanged();
    partial void OnopmerkingChanging(string value);
    partial void OnopmerkingChanged();
    partial void OnlaatstewijzigingChanging(System.DateTime value);
    partial void OnlaatstewijzigingChanged();
    partial void OnaantalLeerlingenChanging(System.Nullable<int> value);
    partial void OnaantalLeerlingenChanged();
    #endregion
		
		public Boekenlijst()
		{
			this._BoekBoekenlijsts = new EntitySet<BoekBoekenlijst>(new Action<BoekBoekenlijst>(this.attach_BoekBoekenlijsts), new Action<BoekBoekenlijst>(this.detach_BoekBoekenlijsts));
			this._Status = default(EntityRef<Status>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klas", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string klas
		{
			get
			{
				return this._klas;
			}
			set
			{
				if ((this._klas != value))
				{
					this.OnklasChanging(value);
					this.SendPropertyChanging();
					this._klas = value;
					this.SendPropertyChanged("klas");
					this.OnklasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusID", DbType="Int NOT NULL")]
		public int statusID
		{
			get
			{
				return this._statusID;
			}
			set
			{
				if ((this._statusID != value))
				{
					if (this._Status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstatusIDChanging(value);
					this.SendPropertyChanging();
					this._statusID = value;
					this.SendPropertyChanged("statusID");
					this.OnstatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opmerking", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string opmerking
		{
			get
			{
				return this._opmerking;
			}
			set
			{
				if ((this._opmerking != value))
				{
					this.OnopmerkingChanging(value);
					this.SendPropertyChanging();
					this._opmerking = value;
					this.SendPropertyChanged("opmerking");
					this.OnopmerkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_laatstewijziging", DbType="Date NOT NULL")]
		public System.DateTime laatstewijziging
		{
			get
			{
				return this._laatstewijziging;
			}
			set
			{
				if ((this._laatstewijziging != value))
				{
					this.OnlaatstewijzigingChanging(value);
					this.SendPropertyChanging();
					this._laatstewijziging = value;
					this.SendPropertyChanged("laatstewijziging");
					this.OnlaatstewijzigingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aantalLeerlingen", DbType="Int")]
		public System.Nullable<int> aantalLeerlingen
		{
			get
			{
				return this._aantalLeerlingen;
			}
			set
			{
				if ((this._aantalLeerlingen != value))
				{
					this.OnaantalLeerlingenChanging(value);
					this.SendPropertyChanging();
					this._aantalLeerlingen = value;
					this.SendPropertyChanged("aantalLeerlingen");
					this.OnaantalLeerlingenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boekenlijst_BoekBoekenlijst", Storage="_BoekBoekenlijsts", ThisKey="klas", OtherKey="klas")]
		public EntitySet<BoekBoekenlijst> BoekBoekenlijsts
		{
			get
			{
				return this._BoekBoekenlijsts;
			}
			set
			{
				this._BoekBoekenlijsts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Boekenlijst", Storage="_Status", ThisKey="statusID", OtherKey="statusID", IsForeignKey=true)]
		public Status Status
		{
			get
			{
				return this._Status.Entity;
			}
			set
			{
				Status previousValue = this._Status.Entity;
				if (((previousValue != value) 
							|| (this._Status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Status.Entity = null;
						previousValue.Boekenlijsts.Remove(this);
					}
					this._Status.Entity = value;
					if ((value != null))
					{
						value.Boekenlijsts.Add(this);
						this._statusID = value.statusID;
					}
					else
					{
						this._statusID = default(int);
					}
					this.SendPropertyChanged("Status");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Boekenlijst = this;
		}
		
		private void detach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Boekenlijst = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorie")]
	public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _categorieID;
		
		private string _naam;
		
		private EntitySet<Boek> _Boeks;
		
		private EntitySet<BoekBoekenlijst> _BoekBoekenlijsts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncategorieIDChanging(string value);
    partial void OncategorieIDChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    #endregion
		
		public Categorie()
		{
			this._Boeks = new EntitySet<Boek>(new Action<Boek>(this.attach_Boeks), new Action<Boek>(this.detach_Boeks));
			this._BoekBoekenlijsts = new EntitySet<BoekBoekenlijst>(new Action<BoekBoekenlijst>(this.attach_BoekBoekenlijsts), new Action<BoekBoekenlijst>(this.detach_BoekBoekenlijsts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categorieID", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string categorieID
		{
			get
			{
				return this._categorieID;
			}
			set
			{
				if ((this._categorieID != value))
				{
					this.OncategorieIDChanging(value);
					this.SendPropertyChanging();
					this._categorieID = value;
					this.SendPropertyChanged("categorieID");
					this.OncategorieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Boek", Storage="_Boeks", ThisKey="categorieID", OtherKey="categorieID")]
		public EntitySet<Boek> Boeks
		{
			get
			{
				return this._Boeks;
			}
			set
			{
				this._Boeks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_BoekBoekenlijst", Storage="_BoekBoekenlijsts", ThisKey="categorieID", OtherKey="categorieID")]
		public EntitySet<BoekBoekenlijst> BoekBoekenlijsts
		{
			get
			{
				return this._BoekBoekenlijsts;
			}
			set
			{
				this._BoekBoekenlijsts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boeks(Boek entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = this;
		}
		
		private void detach_Boeks(Boek entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = null;
		}
		
		private void attach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = this;
		}
		
		private void detach_BoekBoekenlijsts(BoekBoekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Categorie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schoolartikel")]
	public partial class Schoolartikel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _naam;
		
		private decimal _prijs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    partial void OnprijsChanging(decimal value);
    partial void OnprijsChanged();
    #endregion
		
		public Schoolartikel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prijs", DbType="Decimal(8,3) NOT NULL")]
		public decimal prijs
		{
			get
			{
				return this._prijs;
			}
			set
			{
				if ((this._prijs != value))
				{
					this.OnprijsChanging(value);
					this.SendPropertyChanging();
					this._prijs = value;
					this.SendPropertyChanged("prijs");
					this.OnprijsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SchoolartikelBoekenlijst")]
	public partial class SchoolartikelBoekenlijst
	{
		
		private string _klas;
		
		private int _id_schoolartikel;
		
		private System.Nullable<decimal> _prijs;
		
		public SchoolartikelBoekenlijst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klas", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string klas
		{
			get
			{
				return this._klas;
			}
			set
			{
				if ((this._klas != value))
				{
					this._klas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_schoolartikel", DbType="Int NOT NULL")]
		public int id_schoolartikel
		{
			get
			{
				return this._id_schoolartikel;
			}
			set
			{
				if ((this._id_schoolartikel != value))
				{
					this._id_schoolartikel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prijs", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> prijs
		{
			get
			{
				return this._prijs;
			}
			set
			{
				if ((this._prijs != value))
				{
					this._prijs = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status")]
	public partial class Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _statusID;
		
		private string _naam;
		
		private EntitySet<Boekenlijst> _Boekenlijsts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstatusIDChanging(int value);
    partial void OnstatusIDChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    #endregion
		
		public Status()
		{
			this._Boekenlijsts = new EntitySet<Boekenlijst>(new Action<Boekenlijst>(this.attach_Boekenlijsts), new Action<Boekenlijst>(this.detach_Boekenlijsts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int statusID
		{
			get
			{
				return this._statusID;
			}
			set
			{
				if ((this._statusID != value))
				{
					this.OnstatusIDChanging(value);
					this.SendPropertyChanging();
					this._statusID = value;
					this.SendPropertyChanged("statusID");
					this.OnstatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Status_Boekenlijst", Storage="_Boekenlijsts", ThisKey="statusID", OtherKey="statusID")]
		public EntitySet<Boekenlijst> Boekenlijsts
		{
			get
			{
				return this._Boekenlijsts;
			}
			set
			{
				this._Boekenlijsts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boekenlijsts(Boekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Status = this;
		}
		
		private void detach_Boekenlijsts(Boekenlijst entity)
		{
			this.SendPropertyChanging();
			entity.Status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Titularis")]
	public partial class Titulari
	{
		
		private string _username;
		
		private string _klas;
		
		public Titulari()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klas", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string klas
		{
			get
			{
				return this._klas;
			}
			set
			{
				if ((this._klas != value))
				{
					this._klas = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uitgever")]
	public partial class Uitgever : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _uitgeverID;
		
		private string _naam;
		
		private EntitySet<Boek> _Boeks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuitgeverIDChanging(string value);
    partial void OnuitgeverIDChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    #endregion
		
		public Uitgever()
		{
			this._Boeks = new EntitySet<Boek>(new Action<Boek>(this.attach_Boeks), new Action<Boek>(this.detach_Boeks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uitgeverID", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string uitgeverID
		{
			get
			{
				return this._uitgeverID;
			}
			set
			{
				if ((this._uitgeverID != value))
				{
					this.OnuitgeverIDChanging(value);
					this.SendPropertyChanging();
					this._uitgeverID = value;
					this.SendPropertyChanged("uitgeverID");
					this.OnuitgeverIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uitgever_Boek", Storage="_Boeks", ThisKey="uitgeverID", OtherKey="uitgeverID")]
		public EntitySet<Boek> Boeks
		{
			get
			{
				return this._Boeks;
			}
			set
			{
				this._Boeks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boeks(Boek entity)
		{
			this.SendPropertyChanging();
			entity.Uitgever = this;
		}
		
		private void detach_Boeks(Boek entity)
		{
			this.SendPropertyChanging();
			entity.Uitgever = null;
		}
	}
}
#pragma warning restore 1591
